### ISSUE TITLE
[1.19.2] Invalid Player Data upon loading power types with conditions or actions on Forge end

### ISSUE THREAD

**Issue by ChrysanthCow** [MerchantPug/Origins-Addon-Multiloader-Template#1]
~~Wait for this PR to be merged.~~

Wait for an Origins Forge update with this PR

https://github.com/EdwinMindcraft/apoli/pull/1

**Comment by RaymondBlaze** [comment]
I've tried making fields in `MultiloaderDataTypes` to be `Lazy`, and seemed like it worked :)
This could be a temporary solution for now, meaning we can move on and change it whenever Edwin publish a new release with fixes.

**Comment by ChrysanthCow** [comment]
Glad to hear this! I'll implement the changes when I'm next at my PC or if you still have the files, feel free to PR it.
